apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cj
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-cj
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; sleep 10; date
          restartPolicy: OnFailure
